# Generated by Django 5.1.1 on 2025-01-18 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0013_attempt_questions_user_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_postings', models.IntegerField(default=1)),
                ('salary_package', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_type', models.CharField(max_length=50, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(null=True)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
    ]
