# Generated by Django 5.1.1 on 2025-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0014_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='Recruiter licence/'),
        ),
    ]
