# Generated by Django 5.1.1 on 2025-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0015_recruiter_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_materials',
            fields=[
                ('file_num', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=20)),
                ('file_category', models.CharField(blank=True, max_length=20)),
                ('study_files', models.FileField(upload_to='uploaded_study_materials/')),
            ],
        ),
    ]
