# Generated by Django 5.1.1 on 2025-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0016_study_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_upload',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question_dataset', models.FileField(upload_to='media/')),
            ],
        ),
    ]
